### ISSUE TITLE
Requesting db over http returns 301 Moved Permanently

### ISSUE THREAD

**Issue by norepIy** [brightnucleus/country-codes#6]
The 301 response causes parsing issues in `CountryPlugin`'s `generateConfig`, and `composer install` fails with `Undefined offset: 1`. Updating the url line to `const DB_URL      = 'https://dev.maxmind.com/static/csv/codes/iso3166.csv';` fixes this.

Let me know if others are getting similar results and you would like me to submit a PR

**Comment by thedotedge** [comment]
There's one already, hopefully will be merged asap: https://github.com/brightnucleus/country-codes/pull/5

**Comment by SamCritch** [comment]
I'm seeing the same thing. Now I'm trying to work out what we're using the country codes database for. :-)

**Comment by schlessera** [comment]
Fixed in v0.3.1 through #5

**Comment by schlessera** [comment]
Thanks all for the report and the PR!

**Comment by norepIy** [comment]
Thank you!
